#!/bin/bash
shopt -u extglob
top -i -n 1 -b -u $USER 
echo -e "\e[31m^Top non-idle processes for the current user^\e[0m" 
echo $USER
echo -e "\e[31m^Who you are^\e[0m" 
pwd
echo -e "\e[31m^Where you are^\e[0m" 
getent group sudo | cut -d: -f4
echo -e "\e[31m^Users with sudo privileges^\e[0m" 
id -u
echo -e "\e[31m^Your UID^\e[0m" 
